### ISSUE TITLE
filetime 코드 리뷰

### ISSUE THREAD

**Issue by sy0223lee** [Jae211/Project2#15]

**Comment by sy0223lee** [comment]
아래 결과와 같이 수정 시간과 날짜가 잘 출력되는 것을 알 수 있다.
<img width="200" alt="image" src="https://user-images.githubusercontent.com/89008921/167284218-0f14de8d-396a-442e-b014-5352f08a2fb8.png">

**Comment by imdayoung** [comment]
확인 !!

**Comment by Jae211** [comment]
확인했습니다~

**Comment by mouse0429** [comment]
확인했습니다
