### ISSUE TITLE
datecmp 코드 리뷰

### ISSUE THREAD

**Issue by mouse0429** [Jae211/Project2#22]

**Comment by mouse0429** [comment]
각 경우 별 결과 값은 다음과 같다.
#### text1 이 text2 보다 먼저 수정됐을 때
1. 월은 같고 일이 다를 때
`ls - l` 입력 시
![image](https://user-images.githubusercontent.com/68915238/168156013-8a6d7c65-bc78-4a3b-bac9-c8741aa12e5a.png)
실행결과
![image](https://user-images.githubusercontent.com/68915238/168156766-05dfdcd7-bfe4-4382-82f4-9e75c7d842d9.png)
2. 월이 다를 때
`ls - l` 입력 시
![image](https://user-images.githubusercontent.com/68915238/168157273-2841d8ad-e956-4696-bc68-16ca70741a06.png)
실행결과
![image](https://user-images.githubusercontent.com/68915238/168157386-7f223984-cdf2-465b-b886-a46fb0cda456.png)

#### text2가 text1보다 먼저 수정됐을 때
1. 월은 같고 일이 다를 때
`ls - l` 입력 시
![image](https://user-images.githubusercontent.com/68915238/168157746-b71ebbf9-5a59-4797-b46b-03c6f04f87b0.png)
실행결과
![image](https://user-images.githubusercontent.com/68915238/168157800-0ab27e24-deb4-4a00-9bce-8fa8b78e8383.png)
2. 월이 다를 때
`ls - l` 입력 시
![image](https://user-images.githubusercontent.com/68915238/168157891-a829cdfd-525e-4461-bceb-9a91988aa41e.png)
실행결과
![image](https://user-images.githubusercontent.com/68915238/168157962-0dd979a3-ba32-4895-81e5-40a3441067c5.png)

#### text1과 text2가 같은 날짜에 생성됐을 때
`ls - l` 입력 시
![image](https://user-images.githubusercontent.com/68915238/168158068-ac98bf7b-cdc2-4a39-9dcc-3d87c638bee5.png)
실행결과
![image](https://user-images.githubusercontent.com/68915238/168158128-48ca4c0d-da80-4a78-bfb1-2586de63787b.png)

**Comment by imdayoung** [comment]
각 경우별 결과화면 첨부 좋아요! 확인했습니다

**Comment by Jae211** [comment]
확인했습니다~

**Comment by sy0223lee** [comment]
확인했습니다!
