### ISSUE TITLE
timecmp 코드 리뷰

### ISSUE THREAD

**Issue by mouse0429** [Jae211/Project2#23]

**Comment by mouse0429** [comment]
각 경우 별 결과 값은 다음과 같다.

#### text1 이 text2 보다 시간 상 먼저 수정됐을 때
1. 시는 같고 분이 다를 때
`ls - l` 입력 시
![image](https://user-images.githubusercontent.com/68915238/168159131-cab34e86-b540-425a-b90d-5198132dc8ea.png)
실행결과
![image](https://user-images.githubusercontent.com/68915238/168159197-e596268c-6d34-44ff-ab44-1431d73a5f21.png)

2. 시가 다를 때
`ls - l` 입력 시
![image](https://user-images.githubusercontent.com/68915238/168158908-ca6a22b4-57fc-4bb3-a111-3474bc12f399.png)
실행결과
![image](https://user-images.githubusercontent.com/68915238/168158941-6137ebd2-b799-47f6-941c-8a4a7e062815.png)

#### text2 가 text1 보다 시간 상 먼저 수정됐을 때
1. 시는 같고 분이 다를 때
`ls - l` 입력 시
![image](https://user-images.githubusercontent.com/68915238/168159351-4a6c353a-6973-4558-9fab-5cc46d58c80d.png)
실행결과
![image](https://user-images.githubusercontent.com/68915238/168159407-93fad1ee-20a9-457f-9f6c-c78bf2ce92a5.png)
2. 시가 다를 때
`ls - l` 입력 시
![image](https://user-images.githubusercontent.com/68915238/168159486-8e48269d-6f7a-4a22-a803-657fe7dee933.png)
실행결과
![image](https://user-images.githubusercontent.com/68915238/168159543-05227c25-c3e5-4d94-b3a5-239281574249.png)

#### text1과 text2가 시간 상 수정 시간이 같을 때
ls - l` 입력 시
![image](https://user-images.githubusercontent.com/68915238/168158750-babb5286-eb23-48d3-927c-be1cc785954b.png)
실행결과
![image](https://user-images.githubusercontent.com/68915238/168158786-2c23eaac-e43d-4cfa-baf2-1897ae440722.png)

**Comment by imdayoung** [comment]
확인했습니다!

**Comment by Jae211** [comment]
확인했습니다~

**Comment by sy0223lee** [comment]
확인했습니다!
