### ISSUE TITLE
localtime 메모리 관련 이슈

### ISSUE THREAD

**Issue by mouse0429** [Jae211/Project2#24]
time1과 time2를 filetime2 함수에서 출력했을 때 time2로 통일되는 현상 발생
localtime이 공유되는 변수를 사용하기 때문에 뒤에 localtime함수를 통해 할당한 time2의 값이 출력됨

**Comment by mouse0429** [comment]
메일로 다른 함수 사용가능한지 문의 후 localtime_r 로 수정하는 것을 시도해야 할 것 같습니다.

**Comment by sy0223lee** [comment]
메모리 동적 할당도 괜찮은 방법인 것 같습니다

**Comment by Jae211** [comment]
localtime_r로 잘 돌아가는 것 확인했습니다~

**Comment by mouse0429** [comment]
localtime_r 로 해결됐으니 이슈 닫겠습니다!
