### ISSUE TITLE
sizecmp 코드 리뷰

### ISSUE THREAD

**Issue by Jae211** [Jae211/Project2#3]

**Comment by Jae211** [comment]
![image](https://user-images.githubusercontent.com/71889628/167282094-c8a0a0aa-a8c6-4420-9deb-012b02f26d7d.png)
text1, text2의 정보가 위와 같은 상황에서 size compare 실행 시

![image](https://user-images.githubusercontent.com/71889628/167282111-60e67a87-88e7-478a-8ae2-22bc5d6c401b.png)
결과는 위와 같다.

**Comment by imdayoung** [comment]
확인했습니다 ~

**Comment by sy0223lee** [comment]
확인했습니다!

**Comment by mouse0429** [comment]
혹시 사이즈 같은 것도 결과 화면 업로드 가능하신가요?

**Comment by mouse0429** [comment]
이슈명에 filecmp로 되어있는 부분도 sizecmp로 변경하면 가독성면에서 좋을 것 같습니다

**Comment by Jae211** [comment]
![image](https://user-images.githubusercontent.com/71889628/167557832-54c58d57-04e0-48f6-9834-7d948d9a13aa.png)

![image](https://user-images.githubusercontent.com/71889628/167557805-fd91ca11-4939-4435-b1af-d4c216614e52.png)

새로운 예시입니다! 이슈명도 변경 완료했습니다~
