### ISSUE TITLE
blockcmp 코드 리뷰

### ISSUE THREAD

**Issue by Jae211** [Jae211/Project2#6]

**Comment by Jae211** [comment]
![image](https://user-images.githubusercontent.com/71889628/167282152-1c20c8a4-3ce7-4d81-b462-3143c1218053.png)
text1, text2가 위와 같은 상황에서 block compare 실행 시

![image](https://user-images.githubusercontent.com/71889628/167282148-ea208f5c-b38c-4065-9853-f8e12d9d433c.png)
결과는 위와 같다.

**Comment by imdayoung** [comment]
확인했습니다 ~

**Comment by sy0223lee** [comment]
확인했습니다!

**Comment by mouse0429** [comment]
혹시 사이즈 다른 것도 볼 수 있나요?

**Comment by Jae211** [comment]
![image](https://user-images.githubusercontent.com/71889628/167570977-cd94dbb5-86ba-412f-b0e8-eda6b5315bc8.png)

![image](https://user-images.githubusercontent.com/71889628/167571017-6e7aa4f7-63b6-4dd0-8570-da8b00e4b606.png)

사이즈 다른 경우 추가예시입니다~

**Comment by imdayoung** [comment]
> ![image](https://user-images.githubusercontent.com/71889628/167570977-cd94dbb5-86ba-412f-b0e8-eda6b5315bc8.png)
> 
> ![image](https://user-images.githubusercontent.com/71889628/167571017-6e7aa4f7-63b6-4dd0-8570-da8b00e4b606.png)
> 
> 사이즈 다른 경우 추가예시입니다~

확인했습니다!
