### ISSUE TITLE
filestat 코드 리뷰

### ISSUE THREAD

**Issue by imdayoung** [Jae211/Project2#9]

**Comment by imdayoung** [comment]
결과 화면은 다음과 같다.
![image](https://user-images.githubusercontent.com/86220363/167139257-61642fbd-ca08-413f-ba74-3191d0bc1e04.png)

**Comment by Jae211** [comment]
확인 완료 했습니다~

**Comment by sy0223lee** [comment]
확인했습니다!

**Comment by mouse0429** [comment]
확인했습니다.  #12 에서 printf 없애신거 확인했고 결과 보여주려면 printf 가 임시로 필요해서 해당 이슈 화면 업데이트까진 불필요할 것 같습니다. 다만 #8 에서 printf 를 삭제할지는 의논해봐야 할 것 같습니다.
@Jae211 @imdayoung @sy0223lee 
저는 #8 에서는 삭제한 버전 업로드도 괜찮다고 생각합니다.

**Comment by imdayoung** [comment]
> 확인했습니다. #12 에서 printf 없애신거 확인했고 결과 보여주려면 printf 가 임시로 필요해서 해당 이슈 화면 업데이트까진 불필요할 것 같습니다. 다만 #8 에서 printf 를 삭제할지는 의논해봐야 할 것 같습니다. @Jae211 @imdayoung @sy0223lee 저는 #8 에서는 삭제한 버전 업로드도 괜찮다고 생각합니다.

#8 은 삭제한 버전으로 수정했습니다
